name: Generate Graphs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Ensure the token has write permissions

jobs:
  generate-graphs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install graphviz pydot

    - name: Install Graphviz
      run: sudo apt-get install graphviz

    - name: Check for changes in simulator_schemas
      id: check_changes
      run: |
        git fetch origin main
        changes_detected=$(git diff --name-only origin/main | grep 'simulator_schemas/' || true)
        if [ -n "$changes_detected" ]; then
          echo "::set-output name=changes_detected::true"
        else
          echo "::set-output name=changes_detected::false"
        fi

    - name: Generate graphs for all simulators
      if: steps.check_changes.outputs.changes_detected == 'true'
      run: |
        python scripts/generate_graph.py all

    - name: Commit graph images
      if: steps.check_changes.outputs.changes_detected == 'true'
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add -f docs/*.png
        git commit -m 'Generate simulator graphs'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
