name: Generate Instances HTML Table

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-html:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensures the workflow has write access to commit the updated HTML file

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Pull latest changes
      run: git pull origin main

    - name: Generate instances table HTML
      run: |
        python scripts/generate_html_table.py

    - name: Commit and push html table
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add -f docs/instances_table.html
        git commit -m 'Generate instances table HTML' || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
