name: Generate html search framework page

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-html:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensures the workflow has write access to commit the updated HTML file

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy files to docs dir
      run: |
        cp scripts/js_html/search.html docs 
        cp scripts/js_html/search.js docs
        cp scripts/js_html/index.html docs
        cp scripts/js_html/style.css docs
        cp scripts/js_html/objects.html docs
        cp scripts/js_html/objects.js docs
        
        rm -fr docs/simulator_schemas
        mkdir docs/simulator_schemas
        cp simulator_schemas/*.json docs/simulator_schemas

    - name: Commit files copied to docs
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add --force docs/search.*
        git add --force docs/index.html
        git add --force docs/style.css
        git add --force docs/objects.*
        git add --force docs/simulator_schemas/*.json
        git commit -m 'Generate instances search HTML' || echo "No changes to commit"
        git push || echo "Push failed"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
