name: Generate Instances Table Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-image:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib pandas

    - name: Generate instances table image
      run: |
        python scripts/generate_table_image.py

    - name: Commit image
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add docs/instances_table.png
        git commit -m 'Generate instances table image'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
