name: Update Instances Table HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-html:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensures the workflow has write access to commit the new HTML file

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema

    - name: Generate instances HTML
      run: |
        python scripts/generate_table_html.py

    - name: Commit HTML file
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add instances.html
        git commit -m 'Generate instances HTML'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
